SELECT NVL(QUANTITY,0)
FROM FD_DP_MNLY_SHIPMNT
WHERE YYYYMM != '201806';

SELECT YYYYMM, QUANTITY, MS_ID, NVL(QUANTITY,0) AS QTY_1
FROM FD_DP_MNLY_SHIPMNT
WHERE YYYYMM = '201806';

SELECT COUNT(DISTINCT(MS_ID))
FROM FD_DP_MNLY_SHIPMNT;

SELECT COUNT(DISTINCT MS_ID)
FROM FD_DP_MNLY_SHIPMNT
WHERE YYYYMM = '201806';

SELECT YYYYMM, MS_ID, QUANTITY
FROM FD_DP_MNLY_SHIPMNT
WHERE YYYYMM BETWEEN '201804' AND '201806';

SELECT A.YYYYMM
      ,A.MS_ID
      ,B.QUANTITY
FROM FD_DP_MNLY_SHIPMNT A, FD_DP_MNLY_SHIPMNT B
WHERE A.MS_ID = B.MS_ID(+);

SELECT YYYYMM, MS_ID, QUANTITY
FROM FD_DP_MNLY_SHIPMNT
WHERE YYYYMM BETWEEN '201804' AND '201806';

WITH CALENDAR AS
(
    SELECT DISTINCT YYYYMM
    FROM FD_DP_MNLY_SHIPMNT ORDER BY YYYYMM
);

SELECT *
FROM(
    SELECT T1.YYYYMM, T2.MS_ID
    FROM (
            SELECT DISTINCT YYYYMM
            FROM FD_DP_MNLY_SHIPMNT
         ) T1,
         (
            SELECT DISTINCT MS_ID
            FROM FD_DP_MNLY_SHIPMNT
         ) T2
    ) T1
LEFT OUTER JOIN FD_DP_MNLY_SHIPMNT T2
ON T1.YYYYMM = T2.YYYYMM
AND T2.MS_ID = T2.MS_ID
WHERE 1=1
AND YYYYMM BETWEEN '201804' AND '201806';

SELECT *
FROM(
        SELECT T1.YYYYMM
              ,T2.MS_ID
        FROM(
                 SELECT '201804' AS YYYYMM FROM DUAL UNION ALL
                 SELECT '201805' AS YYYYMM FROM DUAL UNION ALL
                 SELECT '201806' AS YYYYMM FROM DUAL 
            )T1
      ,(SELECT DISTINCT T1.MS_ID FROM FD_DP_MNLY_SHIPMNT T1)T2
    )T1
LEFT OUTER JOIN FD_DP_MNLY_SHIPMNT T2
ON T1.MS_ID = T2.MS_ID
AND T1.YYYYMM = T2.YYYYMM
WHERE 1=1
AND T1.YYYYMM BETWEEN '201804' AND '201806';

SELECT *
FROM(
        SELECT T1.YYYYMM, T2.MS_ID
        FROM(
            SELECT DISTINCT YYYYMM
            FROM FD_DP_MNLY_SHIPMNT)T1
            ,(SELECT DISTINCT MS_ID
            FROM FD_DP_MNLY_SHIPMNT)T2
            )T1
LEFT OUTER JOIN FD_DP_MNLY_SHIPMNT T2
ON T1.YYYYMM = T2.YYYYMM
AND T1.MS_ID = T2.MS_ID
WHERE 1=1
AND T1.YYYYMM BETWEEN '201804' AND '201806';


SELECT DISTINCT YYYYMM, MS_ID
      ,SUM(QUANTITY) OVER(PARTITION BY MS_ID) AS QTY
FROM FD_DP_MNLY_SHIPMNT
WHERE 1=1
AND YYYYMM BETWEEN '201804' AND '201806' ORDER BY YYYYMM;

SELECT *
FROM(
        SELECT T1.YYYYMM, T2.MS_ID, T2.QTY
        FROM(
            SELECT DISTINCT YYYYMM FROM FD_DP_MNLY_SHIPMNT)T1
            ,(
                SELECT YYYYMM, MS_ID, SUM(QUANTITY) QTY
                FROM FD_DP_MNLY_SHIPMNT
                WHERE 1=1
                AND YYYYMM BETWEEN '201804' AND '201806'
                GROUP BY YYYYMM, MS_ID)T2
    )T1
LEFT OUTER JOIN FD_DP_MNLY_SHIPMNT T2
ON T1.YYYYMM = T2.YYYYMM
AND T1.MS_ID = T2.MS_ID;

    
SELECT DISTINCT YYYYMM
FROM FD_DP_MNLY_SHIPMNT
ORDER BY YYYYMM;

SELECT COUNT(*)
FROM(
        SELECT MS_ID, SUM(QUANTITY)
        FROM FD_DP_MNLY_SHIPMNT
        GROUP BY MS_ID
        );



WITH CALEN AS
(
    SELECT '201801' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201802' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201803' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201804' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201805' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201806' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201807' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201808' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201809' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201810' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201811' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201812' AS YYYYMM FROM DUAL
)

SELECT T1.YYYYMM
      ,T1.MS_ID
      ,NVL(QTY,0) QTY
FROM(
     SELECT T1.YYYYMM
           ,T2.MS_ID
     FROM(
          SELECT YYYYMM
          FROM CALEN
          WHERE YYYYMM BETWEEN '201804' AND '201806')T1,
         (
          SELECT DISTINCT MS_ID
          FROM FD_DP_MNLY_SHIPMNT)T2
    )T1
LEFT OUTER JOIN(
                SELECT YYYYMM
                      ,MS_ID
                      ,SUM(QUANTITY) QTY
                FROM FD_DP_MNLY_SHIPMNT
                GROUP BY YYYYMM, MS_ID)T2
ON T1.YYYYMM = T2.YYYYMM
AND T1.MS_ID = T2.MS_ID;


SELECT T1.PER_RANK
      ,CASE WHEN T1.PER_RANK >= 0 AND T1.PER_RANK <= 0.05 THEN 'A'
            WHEN T1.PER_RANK >= 0.05 AND T1.PER_RANK <= 0.95 THEN 'B'
        ELSE 'C'
        END AS MS_GR
FROM(
     SELECT QUANTITY
           ,PERCENT_RANK() OVER (ORDER BY QUANTITY DESC) AS PER_RANK
     FROM FD_DP_MNLY_SHIPMNT
     )T1;

WITH CALEN AS
(
    SELECT '201801' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201802' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201803' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201804' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201805' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201806' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201807' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201808' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201809' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201810' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201811' AS YYYYMM FROM DUAL UNION ALL
    SELECT '201812' AS YYYYMM FROM DUAL
)

SELECT T1.*
      ,CASE WHEN T1.PER_RANK >= 0 AND T1.PER_RANK <= 0.05 THEN 'A'
            WHEN T1.PER_RANK >= 0.05 AND T1.PER_RANK <= 0.95 THEN 'B'
       ELSE 'C'
       END AS MS_GR
FROM(
     SELECT T1.YYYYMM
           ,T1.MS_ID
           ,T1.QTY
           ,PERCENT_RANK() OVER (ORDER BY T1.QTY DESC) AS PER_RANK
     FROM(
         SELECT T1.YYYYMM
               ,T1.MS_ID
               ,NVL(QTY,0) QTY
         FROM(
              SELECT T1.YYYYMM
                    ,T2.MS_ID
              FROM(
                   SELECT YYYYMM
                   FROM CALEN
                   WHERE YYYYMM BETWEEN '201804' AND '201806')T1,
                  (
                   SELECT DISTINCT MS_ID
                   FROM FD_DP_MNLY_SHIPMNT)T2
             )T1
         LEFT OUTER JOIN(
                         SELECT YYYYMM
                               ,MS_ID
                               ,SUM(QUANTITY) QTY
                         FROM FD_DP_MNLY_SHIPMNT
                         GROUP BY YYYYMM, MS_ID)T2
         ON T1.YYYYMM = T2.YYYYMM
         AND T1.MS_ID = T2.MS_ID
         )T1
    )T1;


















