SELECT T1.YYYYMM,
       T1.MS_ID,
       T1.SITE_ID,
       T1.QUANTITY 당월판매량,
       T2.QUANTITY 전월판매량,
       T3.QUANTITY 전년동월판매량,
       SUM(CASE WHEN T1.YYYYMM BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(T1.YYYYMM || '01', 'YYYYMMDD'), 1), 'YYYYMM')
                                AND TO_CHAR(ADD_MONTHS(TO_DATE(T1.YYYYMM || '01', 'YYYYMMDD'), 3), 'YYYYMM') THEN T1.QUANTITY ELSE 0 END)
       OVER(PARTITION BY T1.YYYYMM) 최근판매량
-- SUM(COLUMN1) OVER(PARITION BY COLUMN2) : COL2로 그룹핑한 COL1의 SUM
FROM FD_DP_MNLY_SHIPMNT T1
LEFT OUTER JOIN FD_DP_MNLY_SHIPMNT T2
    ON T1.MS_ID = T2.MS_ID
    AND T1.SITE_ID = T2.SITE_ID
    AND T1.YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(T2.YYYYMM || '01', 'YYYYMMDD'), 1),'YYYYMM')
LEFT OUTER JOIN FD_DP_MNLY_SHIPMNT T3
    ON T1.MS_ID = T3.MS_ID
    AND T1.SITE_ID = T3.SITE_ID
    AND T1.YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(T3.YYYYMM || '01', 'YYYYMMDD'), 12),'YYYYMM')
WHERE T1.YYYYMM BETWEEN '201807' AND '201906';


---- TEST -----
SELECT T1.YYYYMM,
       T1.MS_ID,
       T1.SITE_ID,
       SUM(현재월) AS 당월판매량,
       SUM(지난월) AS 전월판매량,
       SUM(삼개월) AS 최근판매량
FROM (
     SELECT :YYYYMM AS YYYYMM,
            T1.MS_ID,
            T1.SITE_ID,
            SUM(CASE WHEN T1.YYYYMM = :YYYYMM THEN T1.QUANTITY ELSE 0 END) AS 현재월,
            SUM(CASE WHEN T1.YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(T1.YYYYMM, 'YYYYMM'),-1),'YYYYMM') THEN T1.QUANTITY ELSE 0 END) AS 지난월,
            SUM(CASE WHEN T1.YYYYMM BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(T1.YYYYMM, 'YYYYMM'), -2), 'YYYYMM') AND :YYYYMM THEN T1.QUANTITY ELSE 0 END) AS 삼개월
     FROM FD_DP_MNLY_SHIPMNT T1
     WHERE 1=1
     GROUP BY YYYYMM,
              T1.MS_ID,
              T1.SITE_ID
     ) T1
WHERE T1.YYYYMM = :YYYYMM
GROUP BY T1.YYYYMM,
         T1.MS_ID,
         T1.SITE_ID;